version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: [ mysqld, --character-set-server=utf8mb4 ,--collation-server=utf8mb4_unicode_ci ]
    environment:
      MYSQL_DATABASE: antenna
      MYSQL_ROOT_PASSWORD: root